---
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: stubhub

manifests:
  rawYaml:
    - _infra/k8s/*

build:
  local:
    push: false                             # (default) don't push to dockerHub
  artifacts:
    - image: javascriptforeverything/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:                                 # Instead of it, build entire image on every change, now only change updated files
        manual:
          - src: 'src/**/*.ts'              # Take all those files 
            dest: .                         # put here

    - image: javascriptforeverything/frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
      sync:                                 
        manual:
          - src: 'src/**/*.ts'              
            dest: .                         

    - image: javascriptforeverything/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:                                 
        manual:
          - src: 'src/**/*.ts'              
            dest: .                         
