apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      name: my-pod
      labels:
        app: nginx

    spec:
      containers:
        - name: my-container
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: nginx-web-port
              containerPort: 80

          resources:
            limits:
              cpu: "750m"          # Use "m" for millicores (0.75 CPU)
              memory: "512Mi"     # Memory value should be "Mi" or "Gi"

            requests:
              cpu: "750m"       # Use "m" for millicores (0.75 CPU)
              memory: "512Mi"   # Memory value should be "Mi" or "Gi"
