apiVersion: v1
kind: LimitRange
metadata:
  name: container-limits
  namespace: dev
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: "4Gi"
      min:
        cpu: "100m"
        memory: "200Mi"
