apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple
spec:
  rules:
  - host: baburhaatbd.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: svc1
            port:
              number: 30001
  tls:
  - hosts:
    - baburhaatbd.com
    secretName: my-cert
status:
  loadBalancer: {}
