---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-multi-path
spec:
  ingressClassName: default
  rules:
  - host: mydomain.com            # Must be bore http, elst throw error. But why ?
    http:
      paths:
      - path: /
        pathType: Prefix          # Prefix = /*   | Exact = /
        backend:
          service:
            name: node-port-service-for-deployment
            port:
              number: 80


