apiVersion: v1
kind: PersistentVolume
metadata:
  name: hostpath-pv
  labels:
    volume: hostpath-volume

spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
