apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx:latest
    imagePullPolicy: IfNotPresent  # <-- Add this line
    ports:
      - containerPort: 80

    volumeMounts:
      - name: hostpath-storage
        mountPath: /app/data

  volumes:
  - name: hostpath-storage
    persistentVolumeClaim:
      claimName: hostpath-pvc
