apiVersion: v1
kind: Pod
metadata:
  name: my-pod-1
spec:
  containers:
  - name: my-container
    image: nginx:latest
    imagePullPolicy: IfNotPresent  # <-- Add this line
    ports:
      - containerPort: 80

    volumeMounts:
      - name: nfs-volume
        mountPath: /app/data

  volumes:
  - name: nfs-volume
    persistentVolumeClaim:
      claimName: nfs-pvc
