apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replica

spec:
  replicas: 3
  selector:
    app: nginx-label

  template:
    metadata:
      name: nginx-container
      labels:
        app: nginx-label

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
