apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replicaset

spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx-label

  template:
    metadata:
      name: nginx-container
      labels:
        app: nginx-label

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
