apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-label

  template:
    metadata:
      name: nginx-container
      labels:
        app: nginx-label

    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
