---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service-for-deployment

spec:
  type: LoadBalancer
  selector:
    app: nginx-label        # it is deployment pod label
  ports:
    - port: 80              # Service's VIP port
      targetPort: 80        # Container's application running port (nginx: 80)

