---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-label                # (2)
  template:
    metadata:
      name: nginx-container
      labels:
        app: nginx-label              # (1)
        web: nginx-app
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: node-port-service-for-deployment
spec:
  type: NodePort            # Expose all Nodes Port for outside (for PAT)
  selector:
    app: nginx-label        # (3) it is deployment pod label
  ports:
    - port: 80              # Service's VIP port
      targetPort: 80        # Container's application running port (nginx: 80)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-multi-path
spec:
  ingressClassName: default
  rules:
  - host: mydomain.com            # Must be bore http, elst throw error. But why ? | /etc/hosts => minikube_ip mydomain.com
    http:
      paths:
      - path: /
        pathType: Prefix          # Prefix = /*   | Exact = /
        backend:
          service:
            name: node-port-service-for-deployment      # (4) Target Service
            port:
              number: 80


# $ curl `minikube ip`:<service-port>
# $ curl mydomain.com:<service-port>

# $ minikube addons enable ingress
# $ curl mydomain.com                                   : => Not working

