---
apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service-for-deployment

spec:
  type: ClusterIP
  selector:
    app: nginx-label        # it is deployment pod label
  ports:
    - port: 80              # Service's VIP port
      targetPort: 80        # Container's application running port (nginx: 80)

