apiVersion: v1
kind: Pod
metadata:
  name: my-pod-2
  labels:
    app: my-pod-label
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent  # <-- Add this line
      ports:
        - containerPort: 80
      volumeMounts:
        - name: myvolume
          mountPath: /data

  restartPolicy: Always
  volumes:
    - name: myvolume
      hostPath:
        path: /tmp/data

