apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: my-pod-label
spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent  # <-- Add this line
      ports:
        - containerPort: 80
      volumeMounts:
        - name: myvolume
          mountPath: /data

    - name: busybox
      image: busybox:latest
      imagePullPolicy: IfNotPresent  # <-- Add this line
      command: ['sh', '-c', 'while true; do echo "hellow"; sleep 1; done']  # 1 sec interval
      volumeMounts:
        - name: myvolume
          mountPath: /tmp/data

  volumes:
    - name: myvolume
      emptyDir: {}

  restartPolicy: Always
