apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment

spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-pod-label

  template:
    metadata:
      name: my-pod
      labels:
        app: my-pod-label

    spec:
      containers:
        - name: nginx
          image: nginx
          imagePullPolicy: IfNotPresent  # <-- Add this line
          ports:
            - containerPort: 80
          volumeMounts:
            - name: myvolume
              mountPath: /data

      restartPolicy: Always
      volumes:
        - name: myvolume
          hostPath:
            path: /app/data

